app/__init__.py
from flask import Flask

app = Flask(__name__)

from app.auth import login
from app.home import index
from app.routes import about
from app.routes import contact
from app.routes import testimonial
from app.routes import forum
from app.routes import support
from app.routes import game
from app.routes import faqs

app.register_blueprint(login.login)
app.register_blueprint(index.index)
app.register_blueprint(about.about)
app.register_blueprint(contact.contact)
app.register_blueprint(testimonial.testimonial)
app.register_blueprint(forum.forum)
app.register_blueprint(support.support)
app.register_blueprint(game.game)
app.register_blueprint(faqs.faqs)

app/routes/about.py
from flask import Blueprint, render_template

about = Blueprint('about',__name__, template_folder='templates')

@about.route('/about')
def About():
    return render_template('about/about.html')

app/routes/contact.py
from flask import Blueprint, render_template, redirect, request

contact = Blueprint('contact', __name__, template_folder="templates")

@contact.route('/contact', methods=['GET', 'POST'])
def Contact():
    return render_template('contact/contact.html')

app/routes/faqs.py
from flask import Blueprint, render_template, redirect, request

faqs = Blueprint('faqs', __name__, template_folder="templates")

@faqs.route('/faqs', methods=['GET', 'POST'])
def Faqs():
    return render_template('faqs/faqs.html')

app/routes/forum.py
from flask import Blueprint, render_template, redirect, request

forum = Blueprint('forum', __name__, template_folder="templates")

@forum.route('/community/forum', methods=['GET', 'POST'])
def Forum():
    return render_template('community/forum.html')

app/routes/game.py
from flask import Blueprint, render_template, redirect, request

game = Blueprint('game', __name__, template_folder="templates")

@game.route('/game', methods=['GET', 'POST'])
def Game():
    return render_template('games/games.html')

app/routes/support.py
from flask import Blueprint, render_template, redirect, request

support = Blueprint('support', __name__, template_folder="templates")

@support.route('/community/support', methods=['GET', 'POST'])
def Support():
    return render_template('community/support.html')

app/routes/testimonial.py
from flask import Blueprint, render_template, redirect, request

testimonial = Blueprint('testimonial', __name__, template_folder="templates")

@testimonial.route('/community/testimonial')
def Testimonial():
    return render_template('community/testimonial.html')

app/templates/about/about.html
{% block main %}
    <h1>Hey from about</h1>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ url_for('static', filename='icon/m-black.png')}}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}"  />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Jaro:opsz@6..72&display=swap" rel="stylesheet">
    <title>The Maze {% block title %}- Home {% endblock %}</title>
</head>
<body>
    {% block Navbar %}{% endblock %}
    {% block Main %}{% endblock %}
</body>
<footer>
    {% block Footer %}{% endblock %}
</footer>
    <script rel="script" type="text/js" href="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
</html>

app/templates/home/index.html
{% extends "base.html" %}
{% block title %} {% endblock %}
{% block Navbar %}
<nav class="nav">
    <div class="nav-brand">
        <img src="{{ url_for('static', filename='icon/m-black.png')}}" alt="m black logo" width="10%"/>
        <h1>THE MAZE</h1>
    </div>
    <div class="nav-link">
        <ul>
            <li>
                <a href="{{url_for('about.About')}}">
                    About Us
                </a>
            </li>
            <li>
                <a href="{{url_for('game.Game')}}">
                    Games
                </a>
            </li>
            <li>
                <a href="{{url_for('forum.Forum')}}">
                    Community
                </a>
            </li>
            <li>
                <a href="{{url_for('support.Support')}}">
                    Support
                </a>
            </li>
            <li>
                <a href="{{url_for('faqs.Faqs')}}">
                    FAQs
                </a>
            </li>
        </ul>
    </div>
    <div class="nav-button">
        <a class="btn-dark" href="{{url_for('contact.Contact')}}">
            Contact
        </a>
        <a class="btn-light" href="{{url_for('login.Login')}}">
            Log In
        </a>
    </div>
</nav>
{% endblock %}

{% block Main %}
<div class="heroe-section">
    <h1 class="lead">Embark on an<br> immersive journey<br> through labyrinthine<br> worlds.</h1>
    <p>Experience the thrill of dynamic maze generation and uncover new <br> discovery at every turn.</p>
    <div class="btn-action">
        <button class="btn-light">
            Download
        </button>
        <button class="btn-dark">
            Learn More
        </button>
    </div>
</div>
<div class="features">
    <div class="col-text">
        <h1 class="lead">Experience the Unpredictable Dynamic Maze Generation For Endless Adventure.</h1>
        <p>With our unqinue dynamic maze generation feature, no two games are ever the same. Prepare for an immersive experience filled with excitement and surprises at every turn.</p>
        <div class="feature-section">
            <div class="feature-01">
                <img src="{{ url_for('static', filename='icon/m-black.png')}}" alt="maze logo" width="20%">
                <h2>Unleash Adventure</h2>
                <p>
                    Explore captivating maze that challenge your skills and keep you engaged from start to finish.
                </p>
            </div>
            <div class="feature-02">
                <img src="{{ url_for('static', filename='icon/m-black.png')}}" alt="maze logo" width="20%">
                <h2>Unleash Adventure</h2>
                <p>
                    Embrace on an adventure where each maze holds secrets waiting to be uncovered.
                </p>
            </div>
        </div>
    </div>
    <div class="col-img">
        <img src="{{ url_for('static', filename='img/maze.jpg')}}" alt='features' width="70%"/>
    </div>
</div>
<div class="feature-section col">
        <div class="col-text">
            <h1 class="lead">Experience Stunning Graphics Powered by SDL2 Engine</h1>
            <p>immerse yourself in mesmerizing landscapes and intricate designs as you navigate through each level. The Cutting-edge SDL2 Engine brings the game to life with its stunning graphics.</p>
        </div>
        <div class="col-img">
            <img src="{{ url_for('static', filename='img/maze.jpg')}}" alt='features' width="70%"/>
        </div>
</div>
<div class="feature-section col">
    <div class="col-text">
        <img src="{{ url_for('static', filename='icon/m-black.png')}}" alt="maze logo" width="15%"/>
        <h1 class="lead">Challenge Yourself with Varying Difficulty Levels.</h1>
        <p>Whether you're beginner or an experienced player, our game offers a range of difficulty levels to suit your skills. Test your limits and push yourself to new heights of mastery.</p>
        <div class="btn-action">
            <button class="btn-dark">Play</button>
            <button>Join ></button>
        </div>
    </div>
    <div class="col-img">
        <img src="{{ url_for('static', filename='img/maze.jpg')}}" alt='features' width="70%"/>
    </div>
</div>
<div class="col-profile">
    <div class="row">
        <img src="{{ url_for('static', filename='icon/m-black.png')}}" alt="maze logo" width="5%"/>
        <h3>The Maze Game challenged me in the ways I never expected. Each level presented a unique puzzle that kept me engaged and excited to discover what was around the next corner. The community aspect of the game added an extra layer of enjoyment, as I was able to connect with fellow players and share strategies.</h3>
        <div class="profile">
            <img src="{{ url_for('static', filename='icon/m-black.png')}}" alt="maze logo" width="5%"/>
            <p>Joseph A.</p>
            <p>Gaming Enthusiast, <span>Ukoth Corp.</span></p>
        </div>
    </div>
</div>
<div class="feature-section col">
    <div class="col-text">
        <h1 class="lead">Connect with the Maze Community</h1>
        <p>Join fellow gamers and explore the maze together. Share tips stategies, and epic quests.</p>
        <div class="btn-action">
            <button class="btn-light">Connect</button>
            <button class="btn-dark">Join</button>
        </div>
    </div>
    <div class="col-img">
        <img src="{{ url_for('static', filename='img/maze.jpg')}}" alt='features' width="70%"/>
    </div>
</div>
<div class="row">
    <h1 class="lead">Stay Updated with Our Newsletter</h1>
    <p>Subscribe to recieve the latest updates, tips and community events.</p>
    <div class="subscribe">
        <input type="email" name="email" placeholder="Enter your email"/>
        <button class="btn-light">Sign Up</button>
    </div>
    <p>by signing up, you agree to our Terms and Conditions.</p>
</div>
<div class="faqs">
    <div class="col-faq">
            <h1>FAQs</h1>
            <p>Find answers to commonly asked questions about the maze Game.</p>
            <button class="btn-dark">Contact</button>
    </div>
    <div class="col-questions">
        <div class="col-faq box">
            <h2>How to Play</h2>
            <p>To play the maze Game, simply navigate through the maze using the arrow keys on your keyboard.The objective is to reach the exit while avoiding obstacles and collecting power-ups along the way.</p>
        </div>
        <div class="col-faq box">
            <h2>Is is free?</h2>
            <p>Yes, the Maze Game is free to download and play. However, there may be in-app purchases available for additional features or content.</p>
        </div>
        <div class="col-faq box">
            <h2>Can I customize my charater?</h2>
            <p>Yes, you can Customize your charater in the Maze Game. There are various skins and accessories available that you can unlock or purchase.</p>
        </div>
        <div class="col-faq box">
            <h2>How often are updates?</h2>
            <p>We strive to provide regular updates to the Maze Game, including bug fixes, new levels, and exciting features, Stay tuned for the latest updates!</p>
        </div>
        <div class="col-faq box">
            <h2>How to join the community?</h2>
            <p>To join the Maze Game community, simply create an account on our official website or connect with other players through our official forums and social media channels.</p>
        </div>
    </div>
</div>
{% endblock %}
{% block Footer %}
<div class="footer">
    <div class="footer-menu">
        <div class="footer-subscribe">
            <h1 class="lead">Stay Updated with Our Newsletter</h1>
            <p>Stay up to date on the latest features and releases by joining our newsletter.</p>
            <div class="subscribe">
                <input type="email" name="email" placeholder="Your email address"/>
                <button class="btn-light">Subscribe</button>
            </div>
            <p>By subscribing, you agree to our Privacy Policy and commite to recieve updates from our Company.</p>
        </div>
        <div class="footer-links">
            <div class="Company">
                <h2>Company</h2>
                <a href="{{url_for('index.Index')}}">Home</a>
                <a href="{{url_for('about.About')}}">About Us</a>
                <a href="{{url_for('contact.Contact')}}">Contact</a>
            </div>
            <div class="Community">
                <h2>Community</h2>
                <a href="{{url_for('login.Login')}}">Login</a>
                <a href="{{url_for('forum.Forum')}}">Forum</a>
                <a href="{{url_for('testimonial.Testimonial')}}">Testimonials</a>
                <a href="#">Github</a>
            </div>
            <div class="Socials">
                <h2>Follow Us</h2>
                <a href="#">Facebook</a>
                <a href="#">Instagram</a>
                <a href="#">Twitter</a>
                <a href="#">LinkedIn</a>
                <a href="#">YouTube</a>
            </div>
        </div>
    </div>
    <div class="footer-rights">
        <p>&copy;2024 Joseph Akaro, All rights Reservered.</p>
        <div class="footer-terms">
            <a href="#">Privacy Policy</a>
            <a href="#">Terms and Conditions</a>
            <a href="#">Cookies Settings</a>
        </div>
    </div>
</div>
{% endblock %}